name: contact_management_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2+1
  path: ^1.9.1
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1 # 🎯 ১. লঞ্চার আইকনের প্যাকেজটি এখানে যোগ করা হলো

# 🎯 ২. লঞ্চার আইকনের ফুল সেটআপ (যাতে আইকন কেটে না গিয়ে সম্পূর্ণ সুন্দর দেখায়)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/mobile.png"

  # অ্যান্ড্রয়েড ওরিও (Android 8.0) এবং তার ওপরের ফোনের জন্য যাতে আইকন ফুল দেখায়:
  adaptive_icon_background: "#FFFFFF" # ব্যাকগ্রাউন্ড কালার সাদা রাখলে লোগোটা ফুটে উঠবে, আপনি চাইলে "#673AB7" (পার্পল) ও দিতে পারেন
  adaptive_icon_foreground: "assets/images/mobile.png"

flutter_native_splash:
  color: "#673AB7"
  image: "assets/images/mobile.png"
  fullscreen: true
  android_gravity: center

  android_12:
    color: "#673AB7"
    image: "assets/images/mobile.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/mobile.png # 🎯 ৩. এখানে পাথটি ঠিক করে দেওয়া হলো